CONTENT = {
    "en": {
        "title": "How to Use: Difference Finder",
        "content": (
            "DIFFERENCE FINDER\n"
            "Compares two files completely, row by row, and shows you what's "
            "unique to each side.\n\n"
            "WHAT TO UPLOAD\n"
            "- File A and File B: the two files you want to compare.\n"
            "- Supported formats: .xlsx, .csv, .txt\n"
            "- The files don't need to match formats - you can compare an "
            ".xlsx against a .csv, for example.\n\n"
            "HEADER ROW\n"
            "- Check \"Files include a header row\" if the first row of your "
            "files is column titles, not data.\n"
            "- Leave it unchecked if your files start straight with data.\n"
            "- Getting this wrong either treats real data as a header (losing "
            "that row) or treats a header as data (showing a false "
            "difference).\n\n"
            "WHAT COUNTS AS A DIFFERENCE\n"
            "- A row must match COMPLETELY (every column) to be treated as "
            "the same entry.\n"
            "- Leading/trailing spaces are ignored when comparing.\n"
            "- Capitalization matters - \"DOC1\" and \"doc1\" are treated as "
            "different values.\n\n"
            "WHAT YOU GET\n"
            "- Missing_From_B: rows that are in File A but not in File B.\n"
            "- Missing_From_A: rows that are in File B but not in File A.\n"
            "- Both are saved next to File A, in the SAME format as whichever "
            "file the rows came from.\n"
            "- If both files match completely, no files are created."
        ),
    },
    "de": {
        "title": "Anleitung: Differenzfinder",
        "content": (
            "DIFFERENZFINDER\n"
            "Vergleicht zwei Dateien vollständig, Zeile für Zeile, und zeigt "
            "dir, was auf jeder Seite einzigartig ist.\n\n"
            "WAS HOCHGELADEN WERDEN SOLL\n"
            "- Datei A und Datei B: die beiden Dateien, die du vergleichen "
            "möchtest.\n"
            "- Unterstützte Formate: .xlsx, .csv, .txt\n"
            "- Die Dateien müssen nicht das gleiche Format haben - du kannst "
            "zum Beispiel eine .xlsx mit einer .csv vergleichen.\n\n"
            "KOPFZEILE\n"
            "- Aktiviere \"Files include a header row\", wenn die erste Zeile "
            "deiner Dateien Spaltentitel statt Daten enthält.\n"
            "- Lasse die Option deaktiviert, wenn deine Dateien direkt mit "
            "Daten beginnen.\n"
            "- Wird dies falsch eingestellt, werden entweder echte Daten als "
            "Kopfzeile behandelt (diese Zeile geht verloren) oder eine "
            "Kopfzeile als Daten behandelt (was einen falschen Unterschied "
            "anzeigt).\n\n"
            "WAS ALS UNTERSCHIED ZÄHLT\n"
            "- Eine Zeile muss VOLLSTÄNDIG (in jeder Spalte) übereinstimmen, "
            "um als derselbe Eintrag zu gelten.\n"
            "- Führende und abschließende Leerzeichen werden beim Vergleich "
            "ignoriert.\n"
            "- Groß- und Kleinschreibung ist relevant - \"DOC1\" und \"doc1\" "
            "gelten als unterschiedliche Werte.\n\n"
            "WAS DU BEKOMMST\n"
            "- Missing_From_B: Zeilen, die in Datei A, aber nicht in Datei B "
            "vorkommen.\n"
            "- Missing_From_A: Zeilen, die in Datei B, aber nicht in Datei A "
            "vorkommen.\n"
            "- Beide werden neben Datei A gespeichert, im GLEICHEN Format wie "
            "die Datei, aus der die jeweilige Zeile stammt.\n"
            "- Stimmen beide Dateien vollständig überein, werden keine "
            "Dateien erstellt."
        ),
    },
}
