CONTENT = {
    "en": {
        "title": "How to Use: Packet Generator",
        "content": (
            "PACKET GENERATOR\n"
            "Takes a list of dates or timestamps and splits them into "
            "contiguous, calendar-aligned packets (date ranges) sized as "
            "close as possible to a target record count, within a "
            "tolerance band.\n\n"
            "WHAT TO UPLOAD\n"
            "- One .txt file with ONE date or timestamp value per line - "
            "no other columns or delimiters.\n"
            "- Supported formats (auto-detected): YYYYMMDD, DDMMYYYY, "
            "YYMMDD, DDMMYY (and '.', '/', '-' separated equivalents), "
            "each optionally followed by a time - glued, space-, or "
            "'T'-separated, with HHMMSS, HH:MM:SS, or just HH:MM. Also "
            "supported: 10-digit Unix epoch seconds and 13-digit epoch "
            "milliseconds.\n"
            "- Values with SAP-style grouping punctuation applied to a "
            "glued number (e.g. \"20.260.713.195.635\" for the timestamp "
            "20260713195635) are handled automatically.\n"
            "- Multiple timestamps landing on the same calendar day all "
            "count toward that day, same as multiple date-only rows would.\n"
            "- A stray header row that doesn't parse under the detected "
            "format is automatically skipped and reported as a warning.\n"
            "- If the file's format is genuinely ambiguous (this can "
            "happen with 2-digit years, since a day-of-month and a "
            "2-digit year can look identical), you'll get a clear error - "
            "use the Sample Value / Its Date fields below to resolve it.\n\n"
            "PACKET SIZE (N)\n"
            "- The target record count for each packet. Required.\n\n"
            "TOLERANCE %\n"
            "- Required. How far above and below N a packet is allowed to "
            "land before it's flagged as a warning, e.g. 20 means the "
            "accepted band is [0.8x, 1.2x] the target.\n\n"
            "START GRANULARITY\n"
            "- Which calendar unit each packet's search starts from: "
            "year (default), half-year, quarter, or month. Whichever is "
            "chosen, the search always cascades down through progressively "
            "finer units (year -> half-year -> quarter -> month -> day) as "
            "far as the data actually requires - it never stops short of "
            "day-level if that's what's needed to land within tolerance.\n"
            "- Pick 'year' for sparser data where whole years make sense "
            "as packets; pick 'month' (or finer) for denser data where "
            "trying whole years every time would just be wasted effort.\n\n"
            "START DATE / END DATE (both optional)\n"
            "- Start Date: records before this are excluded. Leave blank "
            "to start from the earliest date in the file.\n"
            "- End Date: records after this are excluded, and the FINAL "
            "packet's To Date is set to exactly this date.\n"
            "- Leave End Date blank to use the actual last date found in "
            "the data as the final packet's To Date, regardless of its "
            "size.\n"
            "- Format: DD.MM.YYYY\n\n"
            "BUILD BACKWARD (checkbox)\n"
            "- Unchecked (default): packets are built starting from the "
            "oldest date and working toward the newest. The 'doesn't fit "
            "evenly' leftover packet - if any - ends up being the MOST "
            "RECENT data.\n"
            "- Checked: packets are built starting from the most recent "
            "date (or End Date, if given) and working backward toward the "
            "oldest. The leftover packet - if any - ends up being the "
            "OLDEST data instead.\n"
            "- Either way, the output report always lists packets "
            "chronologically, oldest From Date first - only which end "
            "absorbs the leftover packet differs.\n\n"
            "SAMPLE VALUE / ITS DATE (both optional, but required together)\n"
            "- If auto-detection fails or reports an ambiguous format, "
            "copy one raw value exactly as it appears in your file into "
            "Sample Value, and enter the date you know it represents "
            "(DD.MM.YYYY) into Its Date. No knowledge of date-format "
            "syntax is needed - the tool figures out the matching pattern "
            "for you.\n"
            "- Leave both blank to rely on auto-detection.\n\n"
            "HOW BOUNDARIES ARE CHOSEN\n"
            "- Each packet tries the Start Granularity's calendar unit "
            "first; if that unit's count would exceed the tolerance "
            "ceiling, the next finer unit is tried instead (bounded to "
            "that same oversized span), continuing down to day-level if "
            "needed - whichever level actually keeps the packet closest "
            "to N without needlessly splitting further is what's kept.\n"
            "- A separate pass then looks at the whole result and "
            "regroups any packets that ended up severely off target "
            "(e.g. one badly undersized packet sitting right next to a "
            "badly oversized one), redistributing them more evenly.\n\n"
            "WHAT YOU GET\n"
            "- An Excel file (..._PACKETS.xlsx) saved next to the input, "
            "listing From Date / To Date / No. of Files for each packet."
        ),
    },
    "de": {
        "title": "Anleitung: Paketgenerator",
        "content": (
            "PAKETGENERATOR\n"
            "Nimmt eine Liste von Daten oder Zeitstempeln und teilt sie in "
            "zusammenhängende, kalenderausgerichtete Pakete (Datumsbereiche) "
            "auf, die möglichst nah an einer Ziel-Datensatzanzahl liegen, "
            "innerhalb einer Toleranzspanne.\n\n"
            "WAS HOCHGELADEN WERDEN SOLL\n"
            "- Eine .txt-Datei mit GENAU EINEM Datums- oder Zeitstempelwert "
            "pro Zeile - keine weiteren Spalten oder Trennzeichen.\n"
            "- Unterstützte Formate (automatisch erkannt): YYYYMMDD, "
            "DDMMYYYY, YYMMDD, DDMMYY (sowie mit '.', '/', '-' getrennte "
            "Varianten), jeweils optional gefolgt von einer Uhrzeit - "
            "zusammengeschrieben, mit Leerzeichen oder mit 'T' getrennt, im "
            "Format HHMMSS, HH:MM:SS oder nur HH:MM. Ebenfalls "
            "unterstützt: 10-stellige Unix-Epoch-Sekunden und 13-stellige "
            "Epoch-Millisekunden.\n"
            "- Werte mit SAP-typischer Tausendertrennung auf einer "
            "zusammengeschriebenen Zahl (z. B. \"20.260.713.195.635\" für "
            "den Zeitstempel 20260713195635) werden automatisch erkannt.\n"
            "- Mehrere Zeitstempel, die auf denselben Kalendertag fallen, "
            "zählen alle zu diesem Tag, genau wie mehrere reine "
            "Datumszeilen.\n"
            "- Eine einzelne Kopfzeile, die sich nicht mit dem erkannten "
            "Format lesen lässt, wird automatisch übersprungen und als "
            "Warnung gemeldet.\n"
            "- Ist das Format der Datei tatsächlich mehrdeutig (dies kann "
            "bei zweistelligen Jahreszahlen vorkommen, da ein Tag im Monat "
            "und eine zweistellige Jahreszahl identisch aussehen können), "
            "erhältst du eine klare Fehlermeldung - nutze die Felder "
            "Sample Value / Its Date weiter unten, um das Problem zu "
            "lösen.\n\n"
            "PACKET SIZE (N)\n"
            "- Die Ziel-Datensatzanzahl für jedes Paket. Erforderlich.\n\n"
            "TOLERANCE %\n"
            "- Erforderlich. Wie weit ein Paket oberhalb oder unterhalb "
            "von N liegen darf, bevor es als Warnung markiert wird, z. B. "
            "bedeutet 20, dass die akzeptierte Spanne [0,8x, 1,2x] des "
            "Zielwerts beträgt.\n\n"
            "START GRANULARITY\n"
            "- Legt fest, mit welcher Kalendereinheit die Suche für jedes "
            "Paket beginnt: year (Standard), half-year, quarter oder "
            "month. Unabhängig von der Wahl arbeitet sich die Suche immer "
            "schrittweise durch feinere Einheiten (year -> half-year -> "
            "quarter -> month -> day), so weit wie die Daten es "
            "tatsächlich erfordern - sie hält nie vor der Tagesebene an, "
            "wenn das nötig ist, um innerhalb der Toleranz zu bleiben.\n"
            "- Wähle 'year' für dünnere Datenbestände, bei denen ganze "
            "Jahre als Pakete sinnvoll sind; wähle 'month' (oder feiner) "
            "für dichtere Datenbestände, bei denen es jedes Mal "
            "verschwendete Mühe wäre, erst ganze Jahre zu versuchen.\n\n"
            "START DATE / END DATE (beide optional)\n"
            "- Start Date: Datensätze davor werden ausgeschlossen. Leer "
            "lassen, um mit dem frühesten Datum in der Datei zu beginnen.\n"
            "- End Date: Datensätze danach werden ausgeschlossen, und das "
            "To Date des LETZTEN Pakets wird genau auf dieses Datum "
            "gesetzt.\n"
            "- Lasse End Date leer, um das tatsächlich letzte in den Daten "
            "gefundene Datum als To Date des letzten Pakets zu verwenden, "
            "unabhängig von dessen Größe.\n"
            "- Format: DD.MM.YYYY\n\n"
            "BUILD BACKWARD (Kontrollkästchen)\n"
            "- Nicht aktiviert (Standard): Pakete werden ausgehend vom "
            "ältesten Datum aufgebaut und arbeiten sich zum neuesten vor. "
            "Das 'nicht passend aufgehende' Restpaket - falls vorhanden - "
            "enthält dann die AKTUELLSTEN Daten.\n"
            "- Aktiviert: Pakete werden ausgehend vom aktuellsten Datum "
            "(oder vom End Date, falls angegeben) aufgebaut und arbeiten "
            "sich rückwärts zum ältesten vor. Das Restpaket - falls "
            "vorhanden - enthält dann stattdessen die ÄLTESTEN Daten.\n"
            "- In beiden Fällen listet der Ausgabebericht die Pakete immer "
            "chronologisch auf, mit dem ältesten From Date zuerst - nur "
            "welches Ende das Restpaket aufnimmt, unterscheidet sich.\n\n"
            "SAMPLE VALUE / ITS DATE (beide optional, aber nur gemeinsam "
            "erforderlich)\n"
            "- Schlägt die automatische Erkennung fehl oder meldet sie ein "
            "mehrdeutiges Format, kopiere einen Rohwert genau so, wie er "
            "in deiner Datei erscheint, in Sample Value, und trage das "
            "Datum, das er bekanntermaßen darstellt (DD.MM.YYYY), in Its "
            "Date ein. Kenntnisse der Datumsformat-Syntax sind nicht nötig "
            "- das Tool ermittelt das passende Muster für dich.\n"
            "- Lasse beide Felder leer, um dich auf die automatische "
            "Erkennung zu verlassen.\n\n"
            "HOW BOUNDARIES ARE CHOSEN\n"
            "- Jedes Paket versucht zunächst die Kalendereinheit von Start "
            "Granularity; würde die Anzahl dieser Einheit die "
            "Toleranzgrenze überschreiten, wird stattdessen die "
            "nächstfeinere Einheit versucht (begrenzt auf dieselbe "
            "übergroße Spanne), bis hinunter zur Tagesebene, falls nötig - "
            "beibehalten wird die Ebene, die das Paket tatsächlich am "
            "nächsten an N hält, ohne unnötig weiter zu unterteilen.\n"
            "- Ein separater Durchgang betrachtet anschließend das "
            "Gesamtergebnis und gruppiert Pakete neu, die stark vom Ziel "
            "abweichen (z. B. ein deutlich zu kleines Paket direkt neben "
            "einem deutlich zu großen), um sie gleichmäßiger zu "
            "verteilen.\n\n"
            "WHAT YOU GET\n"
            "- Eine Excel-Datei (..._PACKETS.xlsx), gespeichert neben der "
            "Eingabedatei, mit From Date / To Date / No. of Files für "
            "jedes Paket."
        ),
    },
}
